modLoader="javafml"
loaderVersion="[35,)"
license="GNU General Public License v3.0"

[[mods]]
modId="islands"
version="1.3.0"
displayName="Islands"
displayURL="https://www.pixelatedw.xyz/islands"
logoFile="logo.png"
authors="Wynd"
description='''
Simple mod that adds a new World Type for generating and endless ocean filled with islands.

Dev Team :
    Wynd - Progammer 
'''

[[dependencies.islands]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.6,)"
    ordering="NONE"
    side="BOTH"
    
[[dependencies.islands]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"